{application, erlcunia,
	[{description, "Ear training suite"},
	 {vsn, "0.0.0.devel"},
	 {modules, [erlcunia_midi_binary_writer, erlcunia_app,
		    erlcunia_lesson_tutor, erlcunia_supervisor,
		    erlcunia_lesson_player, erlcunia_util,
		    erlcunia_midi_player]},
	 {registered, []},
	 {applications, [kernel, stdlib]},
	 {env, []},
	 {mod, {'erlcunia_app',[]}}]}.
