{'*', [debug_info, report, {outdir, "../ebin/"}]}.
{'erlcunia/*', [debug_info, report, {outdir, "../ebin/erlcunia"}]}.
{'erlcunia/midi/*', [debug_info, report, {outdir, "../ebin/erlcunia/midi"}]}.
{'erlcunia/lesson/*', [debug_info, report, {outdir, "../ebin/erlcunia/lesson"}]}.
